### ISSUE TITLE
Configurar corretamente nome do site que está Mapas Culturais Base Project

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapas-AMAUC#11]
![image.png](https://images.zenhubusercontent.com/622c0d880ed13c26cb9474ee/a0a88e1a-331c-491f-99a6-9deab163daf6)

**Comment by daphnemartinsba** [comment]
A URL mudou e na nova url a descrição  não aparece como baseproject:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/6f259787-c0b1-4b4c-a5f7-38464380ed2b)
