### ISSUE TITLE
instalar Mapas Blame

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapas-AMAUC#12]

**Comment by erleibiazzio** [comment]
Executado na issue #13

**Comment by daphnemartinsba** [comment]
A instalação do plugin mapas blame (também) implementa a aba log de acesso na gestão do usuário. Segue a imagem:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/904fe3dd-add3-4fb3-ad45-0d2faf68c6a3)
