### ISSUE TITLE
desarquivar subsite e corrigir banco de dados

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapas-AMAUC#14]
- [x] passar todas as entidades para o subtiste
- [x] passar todos os roles (exceto saasAdmin e superSaasAdmin) para o subsite
- [x] executar o scritpt recreate-permission-cache.sh para regerar todos os caches de permissão

**Comment by erleibiazzio** [comment]
Todos os procedimentos executados nessa issue foram feitos diretamente no banco de dados

**Comment by daphnemartinsba** [comment]
O arquivamento do subsite gerava alguns bugs como a issue: Arrumar formatação da página dos selos #19
Um outro exemplo, é a impossibilidade de visualizar os agentes daquele subsite.
Ambos os pontos foram resolvidos ao desarquivar.

**Comment by daphnemartinsba** [comment]
O arquivamento do subsite gerava alguns bugs como a issue: Arrumar formatação da página dos selos #19
Um outro exemplo, é a impossibilidade de visualizar os agentes daquele subsite.
Ambos os pontos foram resolvidos ao desarquivar.
