### ISSUE TITLE
Alterar imagens de fundo da home do Mapas

### ISSUE THREAD

**Issue by daphnemartinsba** [hacklabr/mapas-AMAUC#15]
A equipe da AMAUC retornou uma série de imagens que representam os 14 municípios da associação. O ideal é que se consiga juntar imagens até quatro imagens para uma seção, mas deve-se avaliar e optar por aquilo que é melhor para o design.

https://drive.google.com/drive/u/0/folders/1_NQllpVc5-vmoX3C8U8ndeHcUVPuUkwW

**Comment by cesardelucca** [comment]
O Rafa sugeriu que coloque todas as fotos de forma randômica.
Se possível, a 1ª imagem pode ficar fixa (imagem da ponte), e as fotos dos outros blocos seriam randômicas
