### ISSUE TITLE
Inserir links das redes sociais da AMAUC

### ISSUE THREAD

**Issue by cesardelucca** [hacklabr/mapas-AMAUC#16]
site: www.amauc.org.br
facebook: @amaucoficial
youtube: @amaucassociacao

**Comment by daphnemartinsba** [comment]
Ao clicar no símbolo do youtube ocorre o direcionamento para a página da AMAUC no youtube, ao clicar no símbolo de facebook ocorre o direcionamento para a página da AMAUC no facebook.
