### ISSUE TITLE
Alteração do texto da home

### ISSUE THREAD

**Issue by cesardelucca** [hacklabr/mapas-AMAUC#17]
https://docs.google.com/document/d/1rKcBiHJVzSahZfWjf64FgX85XZvAPcprf1pBe7_I7MU/edit

**Comment by daphnemartinsba** [comment]
Segue o texto na home:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/082a98b3-5d27-4867-bcbf-81857b826ded)
