### ISSUE TITLE
Arrumar formatação da página dos selos

### ISSUE THREAD

**Issue by daphnemartinsba** [hacklabr/mapas-AMAUC#19]
A formação da página dos selos está assim:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/875e4b9b-88f0-4d22-b2cb-0fb166787ee7)

**Comment by erleibiazzio** [comment]
![image.png](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/9f8666e7-e03e-425c-8c52-f7041d111765)

O problema aqui me parecia estar relacionado ao subisite estar arquivado. Quando executamos a issue #14 como consequencia resolvemos o problema
