### ISSUE TITLE
Botão ok da seleção do tipo do sub espaço não funciona

### ISSUE THREAD

**Issue by daphnemartinsba** [hacklabr/mapas-AMAUC#20]
Essa issue ocorre nos demais mapas.
No momento, ao criar um subespaço, selecionar seu tipo e clicar em ok, o tipo não consta como selecionado:
![Peek 11-05-2022 10-25.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/1d33a13a-e5b1-4831-aa6c-fa5384bfac4d)

**Comment by erleibiazzio** [comment]
Essa issue será tratada diretamente no core, acompanhar tratativas na issue 2010 do MapasCulturais

**Comment by erleibiazzio** [comment]
Aparentemente seja um problema de resolução dos monitores, aqui testando diretamente no ambiente de DEV do mapas estava tudo OK como mostra imagem abaixo.

![Peek 16-05-2022 14-42.gif](https://images.zenhubusercontent.com/6230838f2e2b42db1a64b6c9/a3981641-0522-40eb-beb0-c42b0d4d45da)
