### ISSUE TITLE
Botão "ou crie e vincule um novo espaço", ao "adicionar local e data" em um evento não funciona

### ISSUE THREAD

**Issue by daphnemartinsba** [hacklabr/mapas-AMAUC#21]
Essa issue ocorre nos demais mapas.
Funcionamento:
![Peek 11-05-2022 10-33.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/6ed74792-4b6e-4cfb-8c72-e4b67a948954)

**Comment by erleibiazzio** [comment]
Issue tradata diretamente no core, acompanhar tratativas na issue 2009 do MapasCulturais
