### ISSUE TITLE
Gestão do usuário: Não pesquisa por evento

### ISSUE THREAD

**Issue by daphnemartinsba** [hacklabr/mapas-AMAUC#22]
Essa issue ocorre nos outros mapas
Mesmo que hajam eventos cadastrados, a gestão do usuário não pesquisa:
![Peek 11-05-2022 10-42.gif](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/b5e72287-3232-42a8-8ae2-38ec9f408eae)

**Comment by erleibiazzio** [comment]
Issue tradata diretamente no core, acompanhar tratativas na issue 2007 do MapasCulturais

**Comment by erleibiazzio** [comment]
Essa issue será tratada diretamente do core, para acompanhar olhar a isse 2014 no repositório MapasCulturais
