### ISSUE TITLE
Imagens dos emails enviados pelo Mapa da AMAUC

### ISSUE THREAD

**Issue by cesardelucca** [hacklabr/mapas-AMAUC#23]
Inserir a imagem do logo do Mapa da AMAUC nos emails enviados pelo sistema: email de validação de login, email de recuperação de senha, entre outros

**Comment by erleibiazzio** [comment]
A imagem foi corrigida, porem tenos uma autenticação no site de DEV e PROD que impede que seja pega essa imagem... testar essa issue apos a remoção dessa autenticação do produção
