### ISSUE TITLE
Configurar ambiente para redirecionar para a ediçao do agente enquanto o perfil não estiver preenchido

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapas-AMAUC#3]

**Comment by daphnemartinsba** [comment]
Resumo:
Ao selecionar uma área de atuação sem preencher uma descrição curta e tentar sair da tela clicando no painel de controle, o direcionamento ocorre. 

- [x] Comportamento Inesperado: **Quando o clique é em alguma entidade no menu, não ocorre direcionamento**. Mas, aparece um alerta informando que ao sair da página do agente as alterações não serão salvas.

- [x] Como ocorre o direcionamento ao clicar em cima do avatar, não é possível deslogar. Comportamento adequado: **Tem que ser possível deslogar**

**Comment by erleibiazzio** [comment]
[ ] A opção para deslogar foi tratada diretamente no core, acompanhar issue 2016 do MapasCulturais

[ ] A segunda tratativa, me parece estar com comportamento esperado quando o usuário vai sair do modo de edição mas tentou efetuar quaisquer alterações, ele avisa que se não salvar os dados serão perdidos

**Comment by daphnemartinsba** [comment]
Resolvida na issue #2016
