### ISSUE TITLE
Logomarca do Mapa da Cultura da AMAUC

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapas-AMAUC#5]
Link com os logos
https://drive.google.com/drive/u/0/folders/10ermwBHTQO0542KxbjYP2P8JO715QtVE

**Comment by daphnemartinsba** [comment]
A logomarca consta no canto superior esquerdo logo abaixo do menu:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/b4e82950-f880-4913-aa5b-35d391ffa194)

Quando há a rolagem da tela na single, passa a compor o header:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/3e1f82dd-e3e7-4a73-9a06-e4d47e36e5ae)
