### ISSUE TITLE
Configurar Captcha no Autenticador

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapas-AMAUC#6]

**Comment by daphnemartinsba** [comment]
Caso tente o acesso sem marcar o captcha, o sistema atualiza a página e mostra a mensagem:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/5d2dfc6e-b355-4387-895c-d5b5505cf003)

Caso marque o captcha, é possível realizar o login:
[Uploading... image.png]
