### ISSUE TITLE
Ajustar horário do dos registros colocando fuso de Brasília

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapas-AMAUC#7]

**Comment by daphnemartinsba** [comment]
Foram realizados testes com os horários de registro do histórico, dos logs e de início das inscrições com o computador configurado no fuso horário de Campo Grande, MS (1 hora a menos que o horário de Brasília). 
Em todos os casos testados os horários condiziam com o fuso de Brasília.
