### ISSUE TITLE
configurar API do CEP Aberto

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapas-AMAUC#9]

**Comment by daphnemartinsba** [comment]
Resumo do relatório:
Ao digitar o CEP o georreferenciamento do ícone o direciona para a região daquele CEP. O logradouro, bairro, município e estado são automaticamente preenchidos. 

- [ ] Confirmar Fluxo: Ao atualizar a informação do CEP, o preenchimento de logradouro, bairro, município e estado é atualizado, contudo, é necessário salvar a alteração, sair do modo de edição e clicar em editar novamente para que ícone seja georreferenciado.
